# Generated by Django 4.1.1 on 2022-09-27 19:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='N/A', max_length=50)),
                ('name_jp', models.CharField(default='N/A', max_length=50)),
                ('age', models.IntegerField()),
                ('birthdate', models.CharField(default='N/A', max_length=50)),
                ('zodiac', models.CharField(default='N/A', max_length=50)),
                ('affiliations', models.CharField(default='N/A', max_length=50)),
                ('title', models.CharField(default='N/A', max_length=50)),
                ('height', models.CharField(default='N/A', max_length=50)),
                ('weight', models.CharField(default='N/A', max_length=50)),
                ('image', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='N/A', max_length=50)),
                ('name_jp', models.CharField(default='N/A', max_length=50)),
                ('model_type', models.CharField(default='N/A', max_length=50)),
                ('pilot', models.CharField(default='N/A', max_length=50)),
                ('soul', models.CharField(default='N/A', max_length=50)),
                ('image', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evangelion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='N/A', max_length=50)),
                ('title_jp', models.CharField(default='N/A', max_length=50)),
                ('type', models.CharField(default='N/A', max_length=50)),
                ('episodes', models.IntegerField()),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), size=None)),
                ('released', models.CharField(default='N/A', max_length=50)),
                ('logo', models.URLField(blank=True, max_length=1024, null=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='Chars', to='api.characters')),
                ('units', models.ManyToManyField(blank=True, related_name='Evas', to='api.evaunits')),
            ],
        ),
    ]
